### ISSUE TITLE
Nested packages

### ISSUE THREAD

**Issue by f0t0n** [artyomtrityak/backbone-package-template#2]
Don't you think that the opportunity to create nested packages may be needed?

**Comment by artyomtrityak** [comment]
mmm, maybe. And the good news that this is supported :)

**Comment by f0t0n** [comment]
Need to create a generator that will provide an ability to generate subpackages.

**Comment by artyomtrityak** [comment]
good idea.

**Comment by f0t0n** [comment]
Actually it's already working in this way.

```
./node_modules/.bin/brunch generate package pack/subpack

```

will create a nested package `pack.subpack`.

If we'll run 

```
./node_modules/.bin/brunch generate package pack
```

after that, then we'll also get files generated for `pack` package.

Therefore the issue can be closed.
