### ISSUE TITLE
Force git to ignore *.css files

### ISSUE THREAD

**Issue by f0t0n** [artyomtrityak/backbone-package-template#21]
Please consider the suggestion to add `*.css` pattern to the `.gitignore`.
They'll appear locally after the build.

**Comment by artyomtrityak** [comment]
yeah, will do it

**Comment by artyomtrityak** [comment]
it's not so simple - we should think about it because there can be libs css. So we can create folder where we will compile our scss. OR i think we should think about public folder and compilation all data to it
