### ISSUE TITLE
Re-think generated package structure

### ISSUE THREAD

**Issue by f0t0n** [artyomtrityak/backbone-package-template#24]
Don't we need to generate packages with pre-created directories `views`, `models`, `collections`, `templates`?

In real life the package content becomes huge and a bit messy so it's hard to quickly find say module of User model within `user_*` files (user_view, user_collection, users_view, user_model...) when the file tree inside the package is flat. For example the organization package in https://github.com/artyomtrityak/backbone-package-example/tree/master/app/packages/organization grows and becomes messy while it's still very simple package.

I guess users will be forced to create such sub-packages manually so we can provide this out of the box.

Also maybe the `app/shared` could be organized in this way.

**Comment by artyomtrityak** [comment]
i think developer can create structure  inside package as he wants.
The big pros of this template - it's only basic structure which can be flexible for needed app

**Comment by f0t0n** [comment]
>  developer can create structure he wants.

Same developer can create package and any files in it instead of use automatic package generating.

I'm suggesting to create these directories by default and allow user to set-up this in configuration for his needs if he doesn't need that directories.
So firstly he will have handy package structure out of the box and also see an example of such kind of configuration.

**Comment by artyomtrityak** [comment]
so you mean create standard MVC structure inside package?

Folders:
- `views`
- `models` (and collections)

**Comment by f0t0n** [comment]
Exactly.
- `views`
- `models`
- `collections`
- `templates`

If user doesn't need it, he'll re-configure it then to meet his needs.

**Comment by artyomtrityak** [comment]
Does it make sense to create also collections folder? Maybe it will be better to put collections into model folder or in top level of package? It should not be more than 1 collection in standard package

**Comment by f0t0n** [comment]
Currently we can put collections in package's root and see how it goes in real life (if we need the separate directory or not).
In my opinion anyway don't need to mess collections with models in one directory, so the separate directory or package root it is.

**Comment by artyomtrityak** [comment]
agreed #25

**Comment by f0t0n** [comment]
:+1:
